### PR TITLE
Adds index to worker.parent so a common lookup is optimized

### PR DESCRIPTION
**Pull request by keithgabryelski**
what it says on the tin.

### CODE REVIEW

**Review by dmaze — CHANGES_REQUESTED** [review]
Can you please `go generate github.com/diffeo/go-coordinate/postgres`?

**Comment by keithgabryelski** [comment]
```el-guapo$ go generate github.com/diffeo/go-coordinate/postgres
github.com/diffeo/go-coordinate/postgres/coordinate_test.go:6: running "cptest": exec: "cptest": executable file not found in $PATH
el-guapo$ brew install cptest
Error: No available formula with the name "cptest" 
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.
el-guapo$  
```

i need more help to understand where i failed.

**Comment by dmaze** [comment]
You need to `go install github.com/diffeo/go-coordinate/cmd/cptest`.  I can't find anywhere I might have written that step down, though.

We've had good luck elsewhere using github.com/stretchr/testify/suite for basically the same role, but porting all of the Coordinate tests to use that (and dropping `cptest`) is probably a bigger task.

**Comment by dmaze** [comment]
Looks good, thanks!

**Pull request merged**
